### ISSUE TITLE
Files never get released/published

### ISSUE THREAD

**Issue by futurelucas4502** [samuelmeuli/action-electron-builder#24] opened 2020-04-28 14:59 UTC
When following the guide [here](https://github.com/marketplace/actions/electron-builder-action) and doing everything stated it doesn't release the files and I get the following error:

```
GitHub release not created  reason=existing type not compatible with publishing type tag=v1.0.28 version=1.0.28 existingType=release publishingType=draft
  • skipped publishing  file=The-City-Of-Truro-Mariners---Management-Console-1.0.28.AppImage reason=existing type not compatible with publishing type tag=v1.0.28 version=1.0.28 existingType=release publishingType=draft
  • skipped publishing  file=latest-linux.yml reason=existing type not compatible with publishing type tag=v1.0.28 version=1.0.28 existingType=release publishingType=draft
```

**Comment by futurelucas4502** [comment] 2020-04-28 14:59
My code is exactly the same as the guide, therefore, hasn't been included

**Comment by samuelmeuli** [comment] 2020-04-29 08:26
Duplicate of https://github.com/samuelmeuli/action-electron-builder/issues/2#issuecomment-555685756

**Closed by samuelmeuli** 2020-04-29 08:26 UTC

**Comment by futurelucas4502** [comment] 2020-04-30 14:40
comment 2 was originally a different issue therefore when I used the search it didn't come up it should really have been done as a separate issue but anyway I'm running electron-builder@^22.4.1 however I still have the issue

**Comment by samuelmeuli** [comment] 2020-05-01 22:31
From your output, it looks like the release you're trying to create already exists?

Anyway, this action is only a wrapper for the `electron-builder` command, so I'd suggest you open an issue in that repo :)

**Comment by futurelucas4502** [comment] 2020-05-01 22:48
@samuelmeuli it's weird as I made a temporary repository so it had no releases and uploaded an existing project from another repository as I'm currently using Travis CI as my builder however wanted to switch to GitHub.... anddd I just realised I didn't change the repository to use in the package.json it's probably that sorry

**Comment by futurelucas4502** [comment] 2020-05-01 23:01
Okay so ive changed the package.json but i still get the same issue so im not sure why it isnt working as my electron works fine

**Comment by DevelopSmith** [comment] 2020-11-04 11:33
Upgrading to `electron-builder@^22.4.1` solved the issue for me.
